<def f='include/boost/thread/exceptions.hpp' l='46' type='void boost::thread_exception::thread_exception(int sys_error_code)'/>
