<def f='include/boost/thread/exceptions.hpp' l='126' type='void boost::thread_resource_error::thread_resource_error()'/>
