<def f='include/boost/system/system_error.hpp' l='36' type='void boost::system::system_error::system_error(int ev, const boost::system::error_category &amp; ecat)'/>
<use f='include/boost/thread/exceptions.hpp' l='43' u='c' c='_ZN5boost16thread_exceptionC1Ev'/>
<use f='include/boost/thread/exceptions.hpp' l='47' u='c' c='_ZN5boost16thread_exceptionC1Ei'/>
