<def f='include/boost/thread/exceptions.hpp' l='138' type='void boost::thread_resource_error::thread_resource_error(int ev, const std::string &amp; what_arg)'/>
