<def f='include/boost/thread/exceptions.hpp' l='42' type='void boost::thread_exception::thread_exception()'/>
