<def f='include/c++/4.9/bits/exception_ptr.h' l='169' type='std::__exception_ptr::exception_ptr std::make_exception_ptr(_Ex __ex)'/>
<use f='include/c++/4.9/future' l='385' u='c' c='_ZNSt13__future_base13_State_baseV216_M_break_promiseESt10unique_ptrINS_12_Result_baseENS2_8_DeleterEE'/>
