<inh f='include/c++/4.9/stdexcept' l='112' c='std::runtime_error'/>
<def f='include/boost/function/function_base.hpp' l='739'/>
<size>16</size>
<doc f='include/boost/function/function_base.hpp' l='735'>/**
 * The bad_function_call exception class is thrown when a boost::function
 * object is invoked
 */</doc>
