<inh f='include/c++/4.9/exception' l='60' c='std::exception'/>
<def f='TrinityCore3.3.5/src/server/shared/Packets/ByteBuffer.h' l='41'/>
<ovr f='TrinityCore3.3.5/src/server/shared/Packets/ByteBuffer.h' l='55' c='ByteBufferPositionException'/>
<ovr f='TrinityCore3.3.5/src/server/shared/Packets/ByteBuffer.h' l='63' c='ByteBufferSourceException'/>
<size>16</size>
<doc f='TrinityCore3.3.5/src/server/shared/Packets/ByteBuffer.h' l='40'>// Root of ByteBuffer exception hierarchy</doc>
<inh f='include/c++/4.9/exception' l='60' c='std::exception'/>
<def f='TrinityCore6.x/src/server/shared/Packets/ByteBuffer.h' l='40'/>
<ovr f='TrinityCore6.x/src/server/shared/Packets/ByteBuffer.h' l='54' c='ByteBufferPositionException'/>
<ovr f='TrinityCore6.x/src/server/shared/Packets/ByteBuffer.h' l='62' c='ByteBufferSourceException'/>
<size>16</size>
<doc f='TrinityCore6.x/src/server/shared/Packets/ByteBuffer.h' l='39'>// Root of ByteBuffer exception hierarchy</doc>
<ovr f='TrinityCore6.x/src/server/game/Server/Packets/PacketUtilities.h' l='53' c='WorldPackets::PacketArrayMaxCapacityException'/>
